# Generated by Django 5.2.5 on 2025-08-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nominee_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
