# Generated by Django 5.2.5 on 2025-08-21 09:32

import insurance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_customuser_nominee_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='nominee_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='aadhaar_back_photo',
            field=models.ImageField(blank=True, null=True, upload_to=insurance.models.aadhaar_upload_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='aadhaar_front_photo',
            field=models.ImageField(blank=True, null=True, upload_to=insurance.models.aadhaar_upload_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pan_photo',
            field=models.FileField(blank=True, null=True, upload_to=insurance.models.pan_upload_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plans',
            field=models.ManyToManyField(blank=True, to='insurance.insuranceplan'),
        ),
    ]
