# Generated by Django 5.2.5 on 2025-08-21 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_transaction_nominee_relation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='plans',
        ),
        migrations.AddField(
            model_name='transaction',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.insuranceplan'),
        ),
    ]
